global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    #scheme: https
    #tls_config:
    #  insecure_skip_verify: true
    static_configs:
      - targets: [ 'frontend', 'backend' ]