version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - "optel-workshop"

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "6000:80"
      - "6001:443"
    networks:
      - "optel-workshop"

  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - "8081:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=FKPPttXNciL8WEbCRot8IXDsGaYreDBRqX7qVdX+kDv0bCpg/g==   # --> 'password'
    networks:
      - "optel-workshop"
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  optel-workshop: